export {
  isConfigured as isEmailConfigured,
  sendWelcome,
  sendOrderConfirmed,
  sendOrderShipped,
  sendOrderDelivered,
  sendBroadcast,
  sendToAllUsers,
  createContact,
  listContacts,
  listSegments,
  createSegment,
  listSentEmails,
  getSentEmail,
  getEmailStats,
} from "./service";
